name: linter

on:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

    - name: Test
      run: |
        node -v
        npm -v
        ls
        pwd
        git status
        git branch

    - name: Install npm dependencies
      run: |
        npm install

    - name: Run ESLint
      run: |
        npm run eslint

    - name: Run Stylelint
      run: |
        npm run stylelint
