name: linter

on:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache .npm
      id: dot_npm_cache_id
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: $${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm dependencies
      if: steps.dot_npm_cache_id.outputs.cache-hit == 'false'
      run: |
        npm ci

    - name: Run ESLint
      run: |
        npm run eslint

    - name: Run Stylelint
      run: |
        npm run stylelint
